# Generated by Django 4.2.9 on 2026-05-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('target_emission', models.FloatField(help_text='Target kg CO2 per period')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
